name-template: $NEXT_PATCH_VERSION
tag-template: $NEXT_PATCH_VERSION
categories:
  - title: 🚀 Features
    label: feature
  - title: 🐛 Bug Fixes
    label: fix
template: |
  ## What’s Changed

  $CHANGES